#!/bin/bash

cp ./lint ./.git/hooks/pre-commit

mod=${1:-./src}
# mod=${mod//\./\/}

printf "\e[1mVerifying version change $mod ...\e[0m\n"
VERSION="$(python3 -m src.version)"
if [ $? -ne 0 ]; then { printf "\e[31mFailed, aborting.\n%s\e[0m\n" "$VERSION" ; exit 1; } fi

printf "\e[1mFormatting code (autopep) $mod ...\e[0m\n"
autopep8 --in-place --aggressive --aggressive --recursive $mod
if [ $? -ne 0 ]; then { printf "\e[31mFailed, aborting.\e[0m\n" ; exit 1; } fi

printf "\e[1mRemoving unused imports (autoflake) $mod ...\e[0m\n"
autoflake --remove-all-unused-imports --in-place -r $mod
if [ $? -ne 0 ]; then { printf "\e[31mFailed, aborting.\e[0m\n" ; exit 1; } fi

printf "\e[1mFormatting code (black) $mod ...\e[0m\n"
black -S --line-length 512 $mod
if [ $? -ne 0 ]; then { printf "\e[31mFailed, aborting.\e[0m\n" ; exit 1; } fi

printf "\e[1mSorting imports (isort) $mod ...\e[0m\n"
isort $mod/*.py
if [ $? -ne 0 ]; then { printf "\e[31mFailed, aborting.\e[0m\n" ; exit 1; } fi

printf "\e[1mAssessing style (pycodestyle) $mod ...\e[0m\n"
pycodestyle --first $mod
if [ $? -ne 0 ]; then { printf "\e[31mFailed, aborting.\e[0m\n" ; exit 1; } fi

printf "\e[1mType Checking (mypy) $mod ...\e[0m\n"
mypy --strict $mod
if [ $? -ne 0 ]; then { printf "\e[31mFailed, aborting.\e[0m\n" ; exit 1; } fi

printf "\e[1mComplexity check $mod ...\e[0m\n"
xenon --max-absolute A --max-modules A --max-average A $mod
if [ $? -ne 0 ]; then { printf "\e[33mWarning.\e[0m\n" ; } fi
xenon --max-absolute B --max-modules A --max-average A $mod
if [ $? -ne 0 ]; then { printf "\e[31mFailed, aborting.\e[0m\n" ; exit 1; } fi

cat > ./.git/hooks/post-commit<< EOF
printf "\e[1mgit push\e[0m\n"
git push
printf "\e[1mgit tag %s\e[0m\n" "$VERSION"
git tag "$VERSION"
if [ $? -ne 0 ]; then { printf "\e[31mError tagging version %s\e[0m\n" "$VERSION" ; } fi
printf "\e[1mgit push --tags\e[0m\n"
git push --tags
if [ $? -ne 0 ]; then { printf "\e[31mError tagging version %s\e[0m\n" "$VERSION" ; } fi
printf "\e[32mSuccess.\e[0m\n"
EOF
chmod +x ./.git/hooks/post-commit

printf "\e[32mSuccess.\e[0m\n"
